export const REGISTER_TOKEN = 'register/token'
export const REGISTER_ID = 'register/id'
export const REGISTER_HEADIMG = 'register/headImg'
export const REGISTER_NICKNAME = 'register/nickName'
export const REGISTER_STATUS = 'register/status'

export const LOGIN_TOKEN = 'login/token'
export const LOGIN_ID = 'login/id'
export const LOGIN_HEADIMG = 'login/headImg'
export const LOGIN_NICKNAME = 'login/nickName'
export const LOGIN_STATUS = 'login/status'
